name: nitemode1
description: Nite Mode for phone.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic_null_safety: ^3.2.4
  url_launcher: ^6.0.12
  material_design_icons_flutter: 5.0.5955-rc.1
  showcaseview: ^1.1.3
  shared_preferences: ^2.0.8
  flutter_launcher_icons: "^0.9.2"
  cupertino_icons: ^1.0.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/astronaut.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/astronaut.svg
    - assets/images/astronaut.png
    - assets/images/moon-solid.png
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/Proxima-Nova-Bold.otf
        - asset: assets/fonts/Proxima-Nova-Regular.ttf
          weight: 800
